# Generated by Django 5.2.17 on 2026-09-05 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSchedule',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('calendar_id', models.CharField(default='suporte-SHM', help_text='ID do Google Calendar corporativo (ex: suporte-SHM ou email@group.calendar.google.com)', max_length=255, verbose_name='ID da Agenda Corporativa Google')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_schedule_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'configuração de agendamento',
                'verbose_name_plural': 'configurações de agendamento',
                'db_table': 'shm_configuracao_schedule',
            },
        ),
    ]
