# Generated by Django 5.2.17 on 2026-09-06 15:36

import apps.core.storage.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao', '0003_alter_reacaocomentario_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reacaocomentario',
            options={'verbose_name': 'reação a comentário', 'verbose_name_plural': 'reações a comentários'},
        ),
        migrations.AddField(
            model_name='anexocomentario',
            name='hash_sha256',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='hash SHA-256'),
        ),
        migrations.AlterField(
            model_name='anexocomentario',
            name='arquivo',
            field=models.FileField(upload_to=apps.core.storage.paths.caminho_anexo_comentario, verbose_name='arquivo'),
        ),
        migrations.AlterField(
            model_name='reacaocomentario',
            name='tipo',
            field=models.CharField(default='curtir', help_text='Identificador textual da reação, ex: curtir, amei, etc.', max_length=20, verbose_name='tipo de reação'),
        ),
    ]
