# Generated by Django 5.2.17 on 2026-09-06 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_cliente_email_google_drive_cliente_gdrive_folder_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSincronizacaoDrive',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem_modelo', models.CharField(db_index=True, max_length=100, verbose_name='modelo de origem')),
                ('origem_id', models.CharField(db_index=True, max_length=100, verbose_name='ID da entidade de origem')),
                ('caminho_local', models.CharField(max_length=500, verbose_name='caminho local relativo')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='nome do arquivo')),
                ('tamanho_bytes', models.BigIntegerField(default=0, verbose_name='tamanho em bytes')),
                ('hash_sha256', models.CharField(db_index=True, max_length=64, verbose_name='hash SHA-256')),
                ('gdrive_file_id', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Google Drive File ID')),
                ('gdrive_web_view_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='link de visualização no Drive')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('sincronizando', 'Sincronizando'), ('sincronizado', 'Sincronizado'), ('erro', 'Erro'), ('excluido', 'Excluído no Drive')], db_index=True, default='pendente', max_length=20, verbose_name='status')),
                ('tentativas', models.IntegerField(default=0, verbose_name='número de tentativas')),
                ('ultimo_erro', models.TextField(blank=True, null=True, verbose_name='última mensagem de erro')),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True, verbose_name='sincronizado em')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_drive', to='clientes.cliente', verbose_name='cliente associado')),
            ],
            options={
                'db_table': 'shm_registro_sincronizacao_drive',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['origem_modelo', 'origem_id'], name='shm_registr_origem__f88c49_idx'), models.Index(fields=['status', 'tentativas'], name='shm_registr_status_ccc393_idx')],
            },
        ),
    ]
