# Generated by Django 5.2.17 on 2026-09-17 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def criar_branding_padrao(apps, schema_editor):
    ConfiguracaoBranding = apps.get_model('core', 'ConfiguracaoBranding')
    if not ConfiguracaoBranding.objects.filter(id=1).exists():
        ConfiguracaoBranding.objects.create(
            id=1,
            razao_social="SHM Tecnologia e Gestão de Contratos Ltda.",
            nome_fantasia="SHM Tecnologia",
            cnpj="",
            telefone_suporte="",
            email_suporte="",
            url_shm="https://shm.empresa.com.br",
            slogan="Suporte Sob Medida e Gestão de Horas",
            representante_nome_completo="",
            representante_cargo="Responsável Técnico",
            representante_documento="",
            mensagem_rodape_relatorio="Documento emitido eletronicamente com validação de integridade criptográfica.",
            cor_primaria_hex="#4F46E5",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoBranding',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('id', models.BigAutoField(default=1, editable=False, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(default='SHM Tecnologia e Gestão de Contratos Ltda.', max_length=200, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(default='SHM Tecnologia', max_length=150, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(blank=True, default='', max_length=20, verbose_name='CNPJ')),
                ('logotipo', models.FileField(blank=True, null=True, upload_to='branding/logos/', verbose_name='logotipo corporativo')),
                ('telefone_suporte', models.CharField(blank=True, default='', max_length=25, verbose_name='telefone de suporte')),
                ('email_suporte', models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail de suporte')),
                ('url_shm', models.URLField(default='https://shm.empresa.com.br', max_length=255, verbose_name='URL base do portal SHM')),
                ('slogan', models.CharField(blank=True, default='Suporte Sob Medida e Gestão de Horas', max_length=255, verbose_name='slogan institucional')),
                ('endereco_completo', models.CharField(blank=True, default='', max_length=300, verbose_name='endereço completo da sede')),
                ('representante_nome_completo', models.CharField(blank=True, default='', max_length=150, verbose_name='nome completo do representante legal')),
                ('representante_cargo', models.CharField(blank=True, default='Responsável Técnico', max_length=100, verbose_name='cargo do representante legal')),
                ('representante_documento', models.CharField(blank=True, default='', max_length=50, verbose_name='documento do representante (CPF/Conselho)')),
                ('representante_assinatura', models.FileField(blank=True, null=True, upload_to='branding/assinaturas/', verbose_name='rubrica ou assinatura digitalizada')),
                ('mensagem_rodape_relatorio', models.TextField(blank=True, default='', verbose_name='mensagem institucional de rodapé do extrato')),
                ('cor_primaria_hex', models.CharField(default='#4F46E5', max_length=7, verbose_name='cor primária institucional (hex)')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_branding_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração de Branding',
                'verbose_name_plural': 'Configurações de Branding',
                'db_table': 'shm_configuracao_branding',
            },
        ),
        migrations.RunPython(criar_branding_padrao, migrations.RunPython.noop),
    ]
