# Generated by Django 5.2.17 on 2026-09-17 07:33

import apps.contratos.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_alter_forensicauditlog_dados_payload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoauditlog',
            name='tipo_evento',
            field=models.CharField(choices=[('criacao', 'Criação de Contrato'), ('aceite', 'Aceite Formalizado'), ('alteracao', 'Alteração Cadastral'), ('conclusao', 'Contrato Concluído'), ('cancelamento', 'Contrato Cancelado'), ('upload_documento', 'Upload de Documento'), ('download_documento', 'Download de Documento'), ('exclusao_documento', 'Exclusão de Documento'), ('atualizacao_emails', 'Atualização de E-mails de Notificação'), ('convite_email', 'Convite de E-mail de Notificação'), ('confirmacao_email', 'Confirmação de E-mail de Notificação'), ('recusa_email', 'Recusa de E-mail de Notificação'), ('download_relatorio', 'Download / Impressão de Relatório'), ('envio_relatorio', 'Envio sob Demanda de Relatório'), ('envio_mensal_relatorio', 'Envio Mensal Automatizado de Relatório'), ('avaliacao_ciclo', 'Avaliação de Ciclo')], max_length=40, verbose_name='tipo de evento'),
        ),
        migrations.CreateModel(
            name='ExtratoOficialGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivo', models.FileField(max_length=500, upload_to=apps.contratos.models.caminho_extrato_contrato, verbose_name='arquivo PDF')),
                ('periodo_referencia', models.CharField(help_text='Formato YYYY-MM', max_length=7, verbose_name='período de referência')),
                ('hash_sha256', models.CharField(db_index=True, max_length=64, verbose_name='hash SHA-256')),
                ('horas_contratadas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='horas contratadas')),
                ('horas_consumidas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='horas consumidas')),
                ('saldo_disponivel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='saldo disponível')),
                ('creditos_migrados', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='créditos migrados')),
                ('debitos_compensados', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='débitos compensados')),
                ('quantidade_ciclos', models.IntegerField(default=0, verbose_name='quantidade de ciclos')),
                ('origem', models.CharField(choices=[('manual_download', 'Download Manual'), ('manual_email', 'Envio Manual por E-mail'), ('mensal_automatico', 'Envio Mensal Automatizado')], default='manual_download', max_length=30, verbose_name='origem')),
                ('destinatarios_notificados', models.JSONField(blank=True, default=list, verbose_name='destinatários notificados')),
                ('gdrive_file_id', models.CharField(blank=True, default='', max_length=150, verbose_name='ID no Google Drive')),
                ('gdrive_file_url', models.URLField(blank=True, default='', verbose_name='URL no Google Drive')),
                ('sincronizado_drive_em', models.DateTimeField(blank=True, null=True, verbose_name='sincronizado com Google Drive em')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extratos_gerados', to='contratos.contrato', verbose_name='contrato')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extratos_gerados', to=settings.AUTH_USER_MODEL, verbose_name='gerado por')),
            ],
            options={
                'verbose_name': 'extrato oficial gerado',
                'verbose_name_plural': 'extratos oficiais gerados',
                'db_table': 'shm_extratos_oficiais',
                'ordering': ['-criado_em'],
            },
        ),
    ]
