# Generated by Django 5.2.17 on 2026-09-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_clienteauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_google_drive',
            field=models.EmailField(blank=True, help_text='E-mail da conta Google para concessão de acesso à pasta corporativa compartilhada', max_length=254, null=True, verbose_name='e-mail Google para Drive'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='ID da pasta Google Drive'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='gdrive_folder_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da pasta no Google Drive'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='gdrive_shared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='compartilhado no Google Drive em'),
        ),
    ]
