# Generated by Django 5.2.17 on 2026-09-06 15:36

import apps.core.storage.paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='contrato',
        ),
        migrations.AddField(
            model_name='anexopedido',
            name='hash_sha256',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='hash SHA-256'),
        ),
        migrations.AlterField(
            model_name='anexopedido',
            name='arquivo',
            field=models.FileField(upload_to=apps.core.storage.paths.caminho_anexo_pedido, verbose_name='arquivo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], db_index=True, default='media', max_length=10, verbose_name='prioridade'),
        ),
    ]
